repos:
- repo: https://github.com/gawsoftpl/pre-commit-hooks
  rev: main
  hooks:
  - id: age-secrets-encrypted
  - id: age-secrets-encrypted-glob
  - id: age-secret-encrypted
  - id: kubernetes-secrets
  - id: sops-secret-encrypted
