- id: age-secrets-encrypted
  name: files encrypted with age
  description: Check that files in argument directory are encrypted with age
  require_serial: true
  entry: bin/age-secrets-encrypted.sh
  language: script
  always_run: true
  args:
  - path
  #files: *
- id: kubernetes-secrets
  name: kubernetes plain secrets
  description: Check that files in argument directory has non encrypted secrets
  require_serial: true
  entry: bin/kubernetes-secrets.sh
  language: script
  always_run: true
  #files: *


